version: "2"
linters:
  default: all
  disable:
    - depguard
    - lll
    - musttag
  settings:
    misspell:
      locale: US
    gosec:
      excludes:
        - G104 # Errors unhandled
        - G304 # Potential file inclusion via variable
  exclusions:
    presets:
      - std-error-handling
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
