name: Go Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.3.0

    - name: Vendorcheck
      shell: bash
      run: |
        go mod tidy
        go mod vendor
        git diff --exit-code
